# Generated by Django 4.0.6 on 2022-07-28 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delivery_driver_match'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='drivers',
        ),
        migrations.DeleteModel(
            name='Delivery_drivers',
        ),
    ]
