# Generated by Django 4.0.6 on 2022-07-29 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_delivery_drivers_delete_delivery_drivers'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='is_busy',
            field=models.BooleanField(default=False),
        ),
    ]
