# Generated by Django 4.0.6 on 2022-07-29 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_driver_is_busy'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_driver_match',
            name='delivery_status',
            field=models.CharField(choices=[('pending', 'pending'), ('delivered', 'delivered')], default='pending', max_length=30),
        ),
    ]
