# Generated by Django 4.0.6 on 2022-07-30 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_delivery_driver_match_delivery_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery_location',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Delivery_accept',
        ),
    ]
