# Generated by Django 4.0.6 on 2022-07-31 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_delivery_location_customer_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Delivery_location',
        ),
    ]
