# Generated by Django 4.0.6 on 2022-07-31 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_delivery_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='delivery_time',
            new_name='delivery_creation_time',
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivered_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
