# Generated by Django 4.0.6 on 2022-08-02 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_payment_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='vendor',
            field=models.ForeignKey(blank=True, default=7, on_delete=django.db.models.deletion.CASCADE, to='api.vendor'),
            preserve_default=False,
        ),
    ]
